### ISSUE TITLE
TypeError: argument 'input': 'NoneType' object cannot be converted to 'PyString

### ISSUE THREAD

**Issue by SimonSG123** [MeltanoLabs/tap-facebook#258]
Whenever I try to run the tap, I get `TypeError: argument 'input': 'NoneType' object cannot be converted to 'PyString'`. This happens with pretty much all streams. I've tried only selecting a few properties per stream, but no luck, even just selecting one or two.

Not sure if this is an issue with our Facebook Ads account, or the tap does not handle empty inputs correctly?

``` 
2024-11-07 16:40:57,901 | INFO     | tap-facebook         | Skipping deselected stream 'adaccounts'.", 'level': 'info', 'timestamp': '2024-11-07T23:40:57.901447Z
 2024-11-07 16:40:57,901 | INFO     | tap-facebook         | Skipping deselected stream 'adimages'.", 'level': 'info', 'timestamp': '2024-11-07T23:40:57.901898Z
 2024-11-07 16:40:57,901 | INFO     | tap-facebook         | Skipping deselected stream 'adlabels'.", 'level': 'info', 'timestamp': '2024-11-07T23:40:57.901980Z
 2024-11-07 16:40:57,901 | INFO     | tap-facebook.ads     | Beginning incremental sync of 'ads'...", 'level': 'info', 'timestamp': '2024-11-07T23:40:57.902051Z
 2024-11-07 16:40:57,901 | INFO     | tap-facebook.ads     | Tap has custom mapper. Using 1 provided map(s).', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.902110Z
 2024-11-07 16:40:57,902 | INFO     | singer_sdk.metrics   | METRIC: {"type": "counter", "metric": "http_request_count", "value": 0, "tags": {"stream": "ads", "endpoint": "/ads?fields=[\'id\', \'account_id\', \'adset_id\', \'campaign_id\', \'bid_type\', \'bid_info\', \'status\', \'updated_time\', \'created_time\', \'name\', \'effective_status\', \'last_updated_by_app_id\', \'source_ad_id\', \'creative\', \'tracking_specs\', \'conversion_specs\', \'recommendations\', \'configured_status\', \'conversion_domain\', \'bid_amount\']"}}', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.902242Z
 2024-11-07 16:40:57,902 | INFO     | singer_sdk.metrics   | METRIC: {"type": "timer", "metric": "sync_duration", "value": 0.00016307830810546875, "tags": {"stream": "ads", "context": {}, "status": "failed"}}', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.902342Z
 2024-11-07 16:40:57,902 | INFO     | singer_sdk.metrics   | METRIC: {"type": "counter", "metric": "record_count", "value": 0, "tags": {"stream": "ads", "context": {}}}', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.902404Z
 2024-11-07 16:40:57,902 | ERROR    | tap-facebook.ads     | An unhandled error occurred while syncing 'ads'", 'level': 'info', 'timestamp': '2024-11-07T23:40:57.903960Z
 Traceback (most recent call last):', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.904037Z
   File "<path>extractors/tap-facebook/venv/lib/python3.11/site-packages/singer_sdk/streams/core.py", line 1203, in sync', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.904091Z
     for _ in self._sync_records(context=context):', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.904146Z
   File "<path>extractors/tap-facebook/venv/lib/python3.11/site-packages/singer_sdk/streams/core.py", line 1097, in _sync_records', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.904193Z
     for idx, record_result in enumerate(self.get_records(current_context)):', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.904232Z
   File "<path>extractors/tap-facebook/venv/lib/python3.11/site-packages/singer_sdk/streams/rest.py", line 585, in get_records', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.904270Z
     for record in self.request_records(context):', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.904307Z
   File "<path>extractors/tap-facebook/venv/lib/python3.11/site-packages/singer_sdk/streams/rest.py", line 390, in request_records', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.904347Z
     prepared_request = self.prepare_request(', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.904452Z
                        ^^^^^^^^^^^^^^^^^^^^^', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.904506Z
   File "<path>extractors/tap-facebook/venv/lib/python3.11/site-packages/singer_sdk/streams/rest.py", line 359, in prepare_request', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.904544Z
     params: dict | str = self.get_url_params(context, next_page_token)', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.904581Z
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.904616Z
   File "<path>extractors/tap-facebook/venv/lib/python3.11/site-packages/tap_facebook/client.py", line 167, in get_url_params', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.904652Z
     ts = pendulum.parse(self.get_starting_replication_key_value(context))', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.904693Z
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.904727Z
   File "<path>extractors/tap-facebook/venv/lib/python3.11/site-packages/pendulum/parser.py", line 30, in parse', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.904775Z
     return _parse(text, **options)', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.904812Z
            ^^^^^^^^^^^^^^^^^^^^^^^', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.904846Z
   File "<path>extractors/tap-facebook/venv/lib/python3.11/site-packages/pendulum/parser.py", line 43, in _parse', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.904881Z
     parsed = base_parse(text, **options)', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.904918Z
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.904954Z
   File "<path>extractors/tap-facebook/venv/lib/python3.11/site-packages/pendulum/parsing/__init__.py", line 78, in parse', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.904991Z
     return _normalize(_parse(text, **_options), **_options)', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.905031Z
                       ^^^^^^^^^^^^^^^^^^^^^^^^', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.905067Z
   File "<path>extractors/tap-facebook/venv/lib/python3.11/site-packages/pendulum/parsing/__init__.py", line 113, in _parse', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.905102Z
     return parse_iso8601(text)', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.905143Z
            ^^^^^^^^^^^^^^^^^^^', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.905178Z
 TypeError: argument 'input': 'NoneType' object cannot be converted to 'PyString'", 'level': 'info', 'timestamp': '2024-11-07T23:40:57.905249Z
 Traceback (most recent call last):', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.905302Z
   File "<path>extractors/tap-facebook/venv/bin/tap-facebook", line 8, in <module>', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.905343Z
     sys.exit(TapFacebook.cli())', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.905456Z
              ^^^^^^^^^^^^^^^^^', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.905503Z
   File "<path>extractors/tap-facebook/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.905542Z
     return self.main(*args, **kwargs)', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.905656Z
            ^^^^^^^^^^^^^^^^^^^^^^^^^^', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.905697Z
   File "<path>extractors/tap-facebook/venv/lib/python3.11/site-packages/click/core.py", line 1078, in main', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.905734Z
     rv = self.invoke(ctx)', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.905772Z
          ^^^^^^^^^^^^^^^^', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.905808Z
   File "<path>extractors/tap-facebook/venv/lib/python3.11/site-packages/singer_sdk/plugin_base.py", line 80, in invoke', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.905852Z
     return super().invoke(ctx)', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.905890Z
            ^^^^^^^^^^^^^^^^^^^', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.905925Z
   File "<path>extractors/tap-facebook/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.905960Z
     return ctx.invoke(self.callback, **ctx.params)', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.905996Z
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.906030Z
   File "<path>extractors/tap-facebook/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.906065Z
     return __callback(*args, **kwargs)', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.906101Z
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.906136Z
   File "<path>extractors/tap-facebook/venv/lib/python3.11/site-packages/singer_sdk/tap_base.py", line 507, in invoke', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.906173Z
     tap.sync_all()', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.906208Z
   File "<path>extractors/tap-facebook/venv/lib/python3.11/site-packages/singer_sdk/tap_base.py", line 466, in sync_all', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.906243Z
     stream.sync()', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.906292Z
   File "<path>extractors/tap-facebook/venv/lib/python3.11/site-packages/singer_sdk/streams/core.py", line 1203, in sync', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.906335Z
     for _ in self._sync_records(context=context):', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.906408Z
   File "<path>extractors/tap-facebook/venv/lib/python3.11/site-packages/singer_sdk/streams/core.py", line 1097, in _sync_records', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.906447Z
     for idx, record_result in enumerate(self.get_records(current_context)):', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.906483Z
   File "<path>extractors/tap-facebook/venv/lib/python3.11/site-packages/singer_sdk/streams/rest.py", line 585, in get_records', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.906517Z
     for record in self.request_records(context):', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.907017Z
   File "<path>extractors/tap-facebook/venv/lib/python3.11/site-packages/singer_sdk/streams/rest.py", line 390, in request_records', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.907089Z
     prepared_request = self.prepare_request(', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.907168Z
                        ^^^^^^^^^^^^^^^^^^^^^', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.907209Z
   File "<path>extractors/tap-facebook/venv/lib/python3.11/site-packages/singer_sdk/streams/rest.py", line 359, in prepare_request', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.907249Z
     params: dict | str = self.get_url_params(context, next_page_token)', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.907288Z
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.907328Z
   File "<path>extractors/tap-facebook/venv/lib/python3.11/site-packages/tap_facebook/client.py", line 167, in get_url_params', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.907383Z
     ts = pendulum.parse(self.get_starting_replication_key_value(context))', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.907425Z
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.907461Z
   File "<path>extractors/tap-facebook/venv/lib/python3.11/site-packages/pendulum/parser.py", line 30, in parse', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.907493Z
     return _parse(text, **options)', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.907939Z
            ^^^^^^^^^^^^^^^^^^^^^^^', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.907995Z
   File "<path>extractors/tap-facebook/venv/lib/python3.11/site-packages/pendulum/parser.py", line 43, in _parse', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.908033Z
     parsed = base_parse(text, **options)', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.908072Z
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.908175Z
   File "<path>extractors/tap-facebook/venv/lib/python3.11/site-packages/pendulum/parsing/__init__.py", line 78, in parse', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.908229Z
     return _normalize(_parse(text, **_options), **_options)', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.908276Z
                       ^^^^^^^^^^^^^^^^^^^^^^^^', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.908319Z
   File "<path>extractors/tap-facebook/venv/lib/python3.11/site-packages/pendulum/parsing/__init__.py", line 113, in _parse', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.908368Z
     return parse_iso8601(text)', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.908407Z
            ^^^^^^^^^^^^^^^^^^^', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.908444Z
 TypeError: argument 'input': 'NoneType' object cannot be converted to 'PyString'", 'level': 'info', 'timestamp': '2024-11-07T23:40:57.908481Z
INFO {'consumer': True, 'producer': False, 'string_id': 'target-sg-analytics-facebook', 'cmd_type': 'elb', 'run_id': '973089af-01c5-4706-be61-461f38364f2a', 'job_name': 'default:tap-facebook-to-target-sg-analytics-facebook', 'stdio': 'stderr', 'name': 'target-sg-analytics-facebook', 'event': 'time=2024-11-07 16:40:57 name=target_postgres level=INFO message=Table \'"ads"\' exists', 'level': 'info', 'timestamp': '2024-11-07T23:40:57.994060Z'}
INFO {'event': 'Incremental state has been updated at 2024-11-07 23:40:58.039710.', 'level': 'info', 'timestamp': '2024-11-07T23:40:58.039726Z'}
ERROR Extractor failed
ERROR {'set_number': 0, 'block_type': 'ExtractLoadBlocks', 'success': False, 'err': RunnerError('Extractor failed'), 'exit_codes': {<PluginType.EXTRACTORS: 'extractors'>: 1}, 'event': 'Block run completed.', 'level': 'error', 'timestamp': '2024-11-07T23:40:58.046096Z'}
Need help fixing this problem? Visit http://melta.no/ for troubleshooting steps, or to
join our friendly Slack community.

Run invocation could not be completed as block failed: Extractor failed
```

**Comment by edgarrmondragon** [comment]
Thanks @SimonSG123, I filed a bug report pointing to offending lines: https://github.com/MeltanoLabs/tap-facebook/issues/272
