### ISSUE TITLE
Failed Validating Type For `account_id` - Not of type 'integer', 'null'

### ISSUE THREAD

**Issue by robg-eb** [MeltanoLabs/tap-facebook#64]
Hello!  I'm trying to use this tap for the first time, and hitting an error when trying to run a complete workflow that validates the schema with `meltano run tap-facebook target-jsonl`.

Note that for privacy, I've changed my actual FB account id in the snippet below to `1234567890`, but otherwise left the log intact:

The specific error:

```
jsonschema.exceptions.ValidationError: '1234567890' is not of type 'integer', 'null' cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
```

My `meltano.yml`:
```
version: 1
default_environment: dev
project_id: <redacted>
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-facebook
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-facebook.git
    config:
      start_date: '2023-01-01T00:00:00Z'
      end_date: '2023-02-01T00:00:00Z'
      api_version: v16.0
    select:
    - ads.*
  loaders:
  - name: target-jsonl
    variant: andyh1203
    pip_url: target-jsonl
```

The full log:
```$ meltano run tap-facebook target-jsonl                                                                                                                                                                                                2023-05-16T22:14:25.721161Z [info     ] Environment 'dev' is active
2023-05-16T22:14:29.530100Z [warning  ] No state was found, complete import.
2023-05-16T22:14:30.052435Z [info     ] 2023-05-16 18:14:30,052 | INFO     | tap-facebook         | Skipping deselected stream 'adaccounts'. cmd_type=elb consumer=False name=tap-facebook producer=True stdio=stderr string_id=tap-facebook
2023-05-16T22:14:30.052694Z [info     ] 2023-05-16 18:14:30,052 | INFO     | tap-facebook         | Skipping deselected stream 'adimages'. cmd_type=elb consumer=False name=tap-facebook producer=True stdio=stderr string_id=tap-facebook
2023-05-16T22:14:30.052765Z [info     ] 2023-05-16 18:14:30,052 | INFO     | tap-facebook         | Skipping deselected stream 'adlabels'. cmd_type=elb consumer=False name=tap-facebook producer=True stdio=stderr string_id=tap-facebook
2023-05-16T22:14:30.052892Z [info     ] 2023-05-16 18:14:30,052 | INFO     | tap-facebook         | Beginning incremental sync of 'ads'... cmd_type=elb consumer=False name=tap-facebook producer=True stdio=stderr string_id=tap-facebook
2023-05-16T22:14:30.052954Z [info     ] 2023-05-16 18:14:30,052 | INFO     | tap-facebook         | Tap has custom mapper. Using 1 provided map(s). cmd_type=elb consumer=False name=tap-facebook producer=True stdio=stderr string_id=tap-facebook
2023-05-16T22:14:31.372900Z [info     ] 2023-05-16 18:14:31,371 | INFO     | singer_sdk.metrics   | METRIC: {"type": "timer", "metric": "http_request_duration", "value": 1.311472, "tags": {"stream": "ads", "endpoint": "/ads?fields=['id', 'account_id', 'adset_id', 'campaign_id', 'bid_type', 'bid_info', 'status', 'updated_time', 'created_time', 'name', 'effective_status', 'last_updated_by_app_id', 'source_ad_id', 'creative', 'tracking_specs', 'conversion_specs', 'recommendations', 'configured_status', 'conversion_domain', 'bid_amount']", "http_status_code": 200, "status": "succeeded"}} cmd_type=elb consumer=False name=tap-facebook producer=True stdio=stderr string_id=tap-facebook
2023-05-16T22:14:31.402002Z [info     ] 2023-05-16 18:14:31,401 | WARNING  | tap-facebook         | Properties ('tracking_specs.post.wall',) were present in the 'ads' stream but not found in catalog schema. Ignoring. cmd_type=elb consumer=False name=tap-facebook producer=True stdio=stderr string_id=tap-facebook
2023-05-16T22:14:31.402750Z [info     ] Traceback (most recent call last): cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-05-16T22:14:31.402899Z [info     ]   File "/Users/robg/eventbrite/data-pipelines/docker/meltano/.meltano/loaders/target-jsonl/venv/bin/target-jsonl", line 8, in <module> cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-05-16T22:14:31.403205Z [info     ]     sys.exit(main())           cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-05-16T22:14:31.403338Z [info     ]   File "/Users/robg/eventbrite/data-pipelines/docker/meltano/.meltano/loaders/target-jsonl/venv/lib/python3.10/site-packages/target_jsonl.py", line 92, in main cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-05-16T22:14:31.403766Z [info     ]     state = persist_messages(  cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-05-16T22:14:31.403914Z [info     ]   File "/Users/robg/eventbrite/data-pipelines/docker/meltano/.meltano/loaders/target-jsonl/venv/lib/python3.10/site-packages/target_jsonl.py", line 54, in persist_messages cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-05-16T22:14:31.404096Z [info     ]     validators[o['stream']].validate((o['record'])) cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-05-16T22:14:31.404188Z [info     ]   File "/Users/robg/eventbrite/data-pipelines/docker/meltano/.meltano/loaders/target-jsonl/venv/lib/python3.10/site-packages/jsonschema/validators.py", line 130, in validate cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-05-16T22:14:31.404352Z [info     ]     raise error                cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-05-16T22:14:31.404484Z [info     ] jsonschema.exceptions.ValidationError: '1234567890' is not of type 'integer', 'null' cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-05-16T22:14:31.404568Z [info     ]                                cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-05-16T22:14:31.404644Z [info     ] Failed validating 'type' in schema['properties']['account_id']: cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-05-16T22:14:31.404717Z [info     ]     {'type': ['integer', 'null']} cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-05-16T22:14:31.404786Z [info     ]                                cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-05-16T22:14:31.404857Z [info     ] On instance['account_id']:     cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-05-16T22:14:31.404925Z [info     ]     '1234567890'        cmd_type=elb consumer=True name=target-jsonl producer=False stdio=stderr string_id=target-jsonl
2023-05-16T22:14:31.422833Z [error    ] Loader failed
2023-05-16T22:14:31.423336Z [error    ] Block run completed.           block_type=ExtractLoadBlocks err=RunnerError('Loader failed') exit_codes={<PluginType.LOADERS: 'loaders'>: 1} set_number=0 success=False
```

The issue seems to be that [this line](https://github.com/MeltanoLabs/tap-facebook/blob/main/tap_facebook/streams.py#L853) defines `account_id` as `IntegerType`, but it is coming in as a string in the response.   Is this an issue with my setup or configuration?  I'm running on Python 3.10.2.

**Comment by edgarrmondragon** [comment]
Hi @robg-eb, thanks for reporting this issue!

We probably want to treat all instances of `account_id` as a string rather than an integer it seems.
